spring:
  datasource:
    url: jdbc:h2:file:./data/PaiSmart;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  kafka:
    listener:
      auto-startup: true

app:
  init:
    elasticsearch:
      enabled: true
    minio:
      enabled: true

security:
  token-cache:
    enabled: false

chat:
  redis:
    enabled: false

org-tag:
  redis:
    enabled: false

knowledge:
  upload:
    redis:
      enabled: false

rag:
  enabled: true

elasticsearch:
  username:
  password:

management:
  health:
    redis:
      enabled: false
    elasticsearch:
      enabled: false

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
