package com.yuki.enterprise_private_rag_qa.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yuki.enterprise_private_rag_qa.client.DeepSeekClient;
import com.yuki.enterprise_private_rag_qa.entity.SearchResult;
import com.yuki.enterprise_private_rag_qa.model.AuditAction;
import com.yuki.enterprise_private_rag_qa.model.RetrievalCitation;
import com.yuki.enterprise_private_rag_qa.service.rag.RagPipeline;
import com.yuki.enterprise_private_rag_qa.utils.AuditSupport;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;
import reactor.core.Disposable;

import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final RagPipeline ragPipeline;
    private final ObjectMapper objectMapper;
    private final AuditService auditService;
    private final OperationMetricsService operationMetricsService;
    private final ConversationService conversationService;
    
    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 当前轮次检索结果，供落库与前端引用展示
    private final Map<String, List<SearchResult>> sessionRetrievalResults = new ConcurrentHashMap<>();
    // 用于取消每个会话正在进行的 LLM 流式请求
    private final Map<String, Disposable> activeStreams = new ConcurrentHashMap<>();
    // 用于停止时保存已生成的部分回答
    private final Map<String, ActiveResponse> activeResponses = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    private final Map<String, Long> chatStartTimes = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      RagPipeline ragPipeline,
                      AuditService auditService,
                      OperationMetricsService operationMetricsService,
                      ConversationService conversationService) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.ragPipeline = ragPipeline;
        this.auditService = auditService;
        this.operationMetricsService = operationMetricsService;
        this.conversationService = conversationService;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        long chatStart = System.currentTimeMillis();
        chatStartTimes.put(session.getId(), chatStart);
        auditService.recordSuccess(userId, userId, AuditAction.CHAT, "conversation",
                session.getId(), AuditSupport.truncate(userMessage, 200), null, null);
        try {
            String sessionId = session.getId();
            stopFlags.remove(sessionId);
            cleanupActiveStream(sessionId);

            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            
            // 为当前会话创建响应构建器
            responseBuilders.put(sessionId, new StringBuilder());
            activeResponses.put(sessionId, new ActiveResponse(userId, conversationId, userMessage));
            
            // 2. 获取对话历史
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", history.size());
            
            // 3. 格式化对话历史（供 RAG Pipeline 使用）
            String chatHistoryStr = formatChatHistory(history);

            // 4. 执行 RAG Pipeline（Stage 1→2→3→4）
            RagPipeline.RagResult ragResult = ragPipeline.execute(userMessage, userId, chatHistoryStr);
            logger.info("RAG Pipeline completed. finalDocs={}, intent={}, usedSupplementary={}, isFallback={}",
                    ragResult.finalDocs().size(),
                    ragResult.queryInfo() != null ? ragResult.queryInfo().getIntent() : "N/A",
                    ragResult.usedSupplementaryRetrieval(),
                    ragResult.isFallback());

            // 5. 构建上下文
            String context = buildContext(ragResult.finalDocs());
            sessionRetrievalResults.put(sessionId, ragResult.finalDocs());
            logger.info("RAG context built, contextLength: {}", context.length());

            // 6. 调用 DeepSeek API 并处理流式响应
            logger.info("调用DeepSeek API生成回复");
            Disposable stream = deepSeekClient.streamResponse(userMessage, context, history,
                chunk -> {
                    if (Boolean.TRUE.equals(stopFlags.get(sessionId))) {
                        logger.debug("检测到停止标志，忽略已取消流中的迟到响应块");
                        return;
                    }

                    // 累积响应内容
                    StringBuilder responseBuilder = responseBuilders.get(sessionId);
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    activeStreams.remove(sessionId);
                    activeResponses.remove(sessionId);
                    if (Boolean.TRUE.equals(stopFlags.get(sessionId))) {
                        logger.info("流式请求已被用户停止，忽略取消后的错误回调，会话ID: {}", sessionId);
                        responseBuilders.remove(sessionId);
                        return;
                    }
                    handleError(session, error);
                    // 发送响应完成通知（错误情况）
                    sendCompletionNotification(session, List.of());
                    // 清理会话响应构建器
                    responseBuilders.remove(sessionId);
                },
                () -> completeResponse(userId, conversationId, userMessage, session));
            activeStreams.put(sessionId, stream);
            
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            // 清理会话响应构建器
            responseBuilders.remove(session.getId());
            activeResponses.remove(session.getId());
            cleanupActiveStream(session.getId());
        }
    }

    private void completeResponse(String userId, String conversationId, String userMessage, WebSocketSession session) {
        String sessionId = session.getId();
        activeStreams.remove(sessionId);
        activeResponses.remove(sessionId);

        if (Boolean.TRUE.equals(stopFlags.get(sessionId))) {
            logger.info("流式请求已被用户停止，忽略完成回调，会话ID: {}", sessionId);
            responseBuilders.remove(sessionId);
            return;
        }

        StringBuilder responseBuilder = responseBuilders.remove(sessionId);
        if (responseBuilder == null) {
            logger.warn("响应完成时找不到响应构建器，会话ID: {}", sessionId);
            return;
        }

        String completeResponse = responseBuilder.toString();
        logger.info("DeepSeek响应流已完成，长度: {}", completeResponse.length());
        Long startedAt = chatStartTimes.remove(sessionId);
        if (startedAt != null) {
            operationMetricsService.recordChatDuration(System.currentTimeMillis() - startedAt);
        }

        List<SearchResult> retrievalResults = sessionRetrievalResults.remove(sessionId);
        sendCompletionNotification(session, retrievalResults);

        if (!completeResponse.isBlank()) {
            persistConversationTurn(userId, conversationId, userMessage, completeResponse, retrievalResults);
            String redisKey = "user:" + userId + ":current_conversation";
            logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);
        } else {
            logger.warn("模型响应为空，跳过写入空助手消息，用户ID: {}, 会话ID: {}", userId, conversationId);
        }

        logger.info("消息处理完成，用户ID: {}", userId);
    }

    private void cleanupActiveStream(String sessionId) {
        Disposable stream = activeStreams.remove(sessionId);
        if (stream != null && !stream.isDisposed()) {
            stream.dispose();
            logger.info("已取消旧的流式请求，会话ID: {}", sessionId);
        }
        activeResponses.remove(sessionId);
        responseBuilders.remove(sessionId);
        sessionRetrievalResults.remove(sessionId);
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);
        
        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }
        
        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }
            
            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    /**
     * 格式化对话历史为 RAG Pipeline 可用的字符串。
     */
    private String formatChatHistory(List<Map<String, String>> history) {
        if (history == null || history.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        for (Map<String, String> msg : history) {
            String role = msg.get("role");
            String content = msg.get("content");
            if (content == null || content.isBlank()) continue;
            if ("user".equals(role)) {
                sb.append("用户: ").append(content).append("\n");
            } else if ("assistant".equals(role)) {
                sb.append("助手: ").append(content).append("\n");
            }
        }
        return sb.toString();
    }

    private void persistConversationTurn(String userId,
                                         String conversationId,
                                         String userMessage,
                                         String response,
                                         List<SearchResult> retrievalResults) {
        List<RetrievalCitation> citations = ConversationService.buildCitations(
                retrievalResults == null ? List.of() : retrievalResults);
        updateConversationHistory(conversationId, userMessage, response, citations);
        try {
            conversationService.recordConversation(
                    userId, userMessage, response, conversationId, retrievalResults);
        } catch (Exception e) {
            logger.error("对话落库失败，用户ID: {}, 会话ID: {}, 错误: {}", userId, conversationId, e.getMessage(), e);
        }
    }

    private void updateConversationHistory(String conversationId,
                                           String userMessage,
                                           String response,
                                           List<RetrievalCitation> citations) {
        String key = "conversation:" + conversationId;
        List<Map<String, String>> history = getConversationHistory(conversationId);
        
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        
        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);
        
        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        if (citations != null && !citations.isEmpty()) {
            try {
                assistantMsgMap.put("citations", objectMapper.writeValueAsString(citations));
            } catch (JsonProcessingException e) {
                logger.warn("Redis 会话引用序列化失败: {}", e.getMessage());
            }
        }
        history.add(assistantMsgMap);
        
        // 限制历史记录长度，保留最近的20条消息
        if (history.size() > 20) {
            history = history.subList(history.size() - 20, history.size());
        }
        
        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private String buildContext(List<SearchResult> searchResults) {
        if (searchResults == null || searchResults.isEmpty()) {
            // 返回空字符串，让 DeepSeekClient 按"无检索结果"逻辑处理
            return "";
        }

        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = result.getParentTextContent() != null && !result.getParentTextContent().isBlank()
                    ? result.getParentTextContent()
                    : result.getTextContent();
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            String parentLabel = result.getParentId() != null ? result.getParentId() : "unknown-parent";
            context.append(String.format("[来源#%d: %s]\nparent_id: %s\n%s\n\n", i + 1, fileLabel, parentLabel, snippet));
        }
        return context.toString();
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 检查是否需要停止发送
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            // 将chunk包装成JSON格式，匹配前端期望的数据结构
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session, List<SearchResult> retrievalResults) {
        try {
            long currentTime = System.currentTimeMillis();
            List<RetrievalCitation> citations = ConversationService.buildCitations(
                    retrievalResults == null ? List.of() : retrievalResults);
            Map<String, Object> notification = new HashMap<>();
            notification.put("type", "completion");
            notification.put("status", "finished");
            notification.put("message", "响应已完成");
            notification.put("timestamp", currentTime);
            notification.put("date", java.time.LocalDateTime.now().toString());
            if (!citations.isEmpty()) {
                notification.put("citations", citations);
            }
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            session.sendMessage(new TextMessage(errorJson));
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应 
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);
        
        // 设置停止标志
        stopFlags.put(sessionId, true);

        Disposable stream = activeStreams.remove(sessionId);
        if (stream != null && !stream.isDisposed()) {
            stream.dispose();
            logger.info("已取消正在进行的流式请求，会话ID: {}", sessionId);
        } else {
            logger.info("停止请求未找到正在进行的流式请求，会话ID: {}", sessionId);
        }

        ActiveResponse activeResponse =         activeResponses.remove(sessionId);
        StringBuilder partialBuilder = responseBuilders.remove(sessionId);
        List<SearchResult> retrievalResults = sessionRetrievalResults.remove(sessionId);
        if (activeResponse != null && partialBuilder != null && !partialBuilder.toString().isBlank()) {
            String partialResponse = partialBuilder + "\n\n（回答已被用户停止）";
            persistConversationTurn(
                    activeResponse.userId(),
                    activeResponse.conversationId(),
                    activeResponse.userMessage(),
                    partialResponse,
                    retrievalResults
            );
            logger.info("已保存用户停止前的部分回答，会话ID: {}, 长度: {}", sessionId, partialResponse.length());
        }
        
        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop", 
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }
        
        // 延迟清理停止标志，拦截取消后可能到达的少量迟到 chunk。
        new Thread(() -> {
            try {
                Thread.sleep(60000);
                stopFlags.remove(sessionId);
                logger.debug("已清理停止标志，会话ID: {}", sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }

    private record ActiveResponse(String userId, String conversationId, String userMessage) {
    }
}
